repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        exclude: ^containers/.*
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-json
        exclude: ^tsconfig.json

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.11.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  - repo: local
    hooks:
      - id: prettier
        name: Run prettier
        entry: npm run format:write
        language: node
        files: \.(js|json)$
        types_or: [file]

      - id: eslint
        name: Run eslint
        entry: npm run lint
        language: node
        files: \.(ts|tsx)$
        types_or: [file]
